name: Grab EPG and Push

on:
  schedule:
    - cron: "0 4 * * *" # Every day at 4 AM UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false


    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: epg

    - name: Run EPG Grab
      run: |
        npm run grab --- --channels=../Main-playlists/epg.xml --maxConnections=10 --days=3
      working-directory: epg

    - name: Check for guide.xml
      run: |
        echo "Checking epg/ directory..."
        ls -la epg
        cat epg/guide.xml || echo "No guide.xml found"


    - name: Commit and Push Changes
      env:
        TOKEN: ${{ secrets.GH_PAT }}
      run: |
        git config user.name "Jamesh6210"
        git config user.email "adidassport2016@gmail.com"
        git add -A
        git commit -m "Auto-updated guide.xml" || echo "No changes to commit"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/Jamesh6210/m3u-playlists.git
        git push origin main
